name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '343.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY_FILE }}

    - name: Configure Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name:${{ github.sha }} .

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet app.yaml
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY_FILE }}


